name: newpost

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      AWS_BUCK: ${{ secrets.AWS_BUCK }}
      AWS_PSWD: ${{ secrets.AWS_PSWD }}
      AWS_REGN: ${{ secrets.AWS_REGN }}
      AWS_USER: ${{ secrets.AWS_USER }}
      BSKY_USER: ${{ secrets.BSKY_USER }}
      BSKY_PSWD: ${{ secrets.BSKY_PSWD }}
      
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
        
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install atproto
          pip install boto3
          pip install pillow

      - name: running bot
        run: python main.py
